name: 'Prepare'
description: 'Prepares the node environment and installs npm packages'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json

    - name: Install packages
      shell: bash
      run: npm ci
