name: Autofix

on:
  pull_request:

permissions:
  contents: write

jobs:
  with-biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Biome CI
        run: npm run ci

      - name: Config Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Commit changes
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const git = require('simple-git')();
            const changes = await git.diffSummary();
            if (changes.files.length > 0) {
              await git.add('./*');
              await git.commit('chore: apply automated fixes');
              await git.push();
            }
