name: Validate

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build
        run: npm run build

      - name: Verify
        run: npm run verify

      - name: Prepare playground
        run: npx yalc publish && npm run playground:install

      - name: Tests
        run: npm run test

      - name: Biome CI
        run: npm run ci
